TENTUKAN LIBRARY YANG AKAN DIGUNAKAN

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

LOAD DATASET

In [2]:
Maternal_dataset = pd.read_csv('Maternal Health Risk Data Set.csv')

In [3]:
Maternal_dataset.head()

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86          2
1   35         140           90  13.0      98.0         70          2
2   29          90           70   8.0     100.0         80          2
3   30         140           85   7.0      98.0         70          2
4   35         120           60   6.1      98.0         76          0

In [4]:
Maternal_dataset.shape

(1014, 7)

In [5]:
Maternal_dataset['RiskLevel'].value_counts()

0    406
1    336
2    272
Name: RiskLevel, dtype: int64

In [6]:
#memisahkan data dan lebel
X = Maternal_dataset.drop(columns='RiskLevel', axis=1)
Y = Maternal_dataset['RiskLevel']

In [7]:
print(X)

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
0      25         130           80  15.0      98.0         86
1      35         140           90  13.0      98.0         70
2      29          90           70   8.0     100.0         80
3      30         140           85   7.0      98.0         70
4      35         120           60   6.1      98.0         76
...   ...         ...          ...   ...       ...        ...
1009   22         120           60  15.0      98.0         80
1010   55         120           90  18.0      98.0         60
1011   35          85           60  19.0      98.0         86
1012   43         120           90  18.0      98.0         70
1013   32         120           65   6.0     101.0         76

[1014 rows x 6 columns]


In [8]:
print(Y)

0       2
1       2
2       2
3       2
4       0
       ..
1009    2
1010    2
1011    2
1012    2
1013    1
Name: RiskLevel, Length: 1014, dtype: int64


STANDARISASI DATA

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(X)

StandardScaler()

In [11]:
standarized_data = scaler.transform(X)

In [12]:
print(standarized_data)

[[-0.36173812  0.91339632  0.25502279  1.90589019 -0.4852155   1.44695615]
 [ 0.38077697  1.45702716  0.97553854  1.29833966 -0.4852155  -0.53208757]
 [-0.06473208 -1.26112705 -0.46549297 -0.22053665  0.97388449  0.70481475]
 ...
 [ 0.38077697 -1.53294248 -1.18600873  3.12099124 -0.4852155   1.44695615]
 [ 0.97478904  0.36976548  0.97553854  2.81721597 -0.4852155  -0.53208757]
 [ 0.15802244  0.36976548 -0.82575085 -0.82808717  1.70343448  0.21005383]]


In [13]:
X = standarized_data
Y = Maternal_dataset['RiskLevel']

In [14]:
print(X)
print(Y)

[[-0.36173812  0.91339632  0.25502279  1.90589019 -0.4852155   1.44695615]
 [ 0.38077697  1.45702716  0.97553854  1.29833966 -0.4852155  -0.53208757]
 [-0.06473208 -1.26112705 -0.46549297 -0.22053665  0.97388449  0.70481475]
 ...
 [ 0.38077697 -1.53294248 -1.18600873  3.12099124 -0.4852155   1.44695615]
 [ 0.97478904  0.36976548  0.97553854  2.81721597 -0.4852155  -0.53208757]
 [ 0.15802244  0.36976548 -0.82575085 -0.82808717  1.70343448  0.21005383]]
0       2
1       2
2       2
3       2
4       0
       ..
1009    2
1010    2
1011    2
1012    2
1013    1
Name: RiskLevel, Length: 1014, dtype: int64


MEMISAHKAN DATA TRAINING DAN DATA TESTING

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [16]:
print(X.shape, X_train.shape, X_test.shape)

(1014, 6) (811, 6) (203, 6)


MEMBUAT DATA LATIH MENGGUNAKAN ALGORIGMA SVM

In [17]:
classifier = svm.SVC(kernel='linear')

In [18]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

MEMBUAT MODEL EVALUASI UNTUK MENGUKUR AKURASI

In [19]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [20]:
print('akurasi data training adalah =', training_data_accuracy)

akurasi data training adalah = 0.6621454993834772


In [21]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [22]:
print('akurasi data testing adalah =', test_data_accuracy)

akurasi data testing adalah = 0.5960591133004927


MEMBUAT MODEL PREDIKSI

In [25]:
input_data = (15,120,80,7.01,98,70)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

std_data = scaler.transform(input_data_reshape)

print(std_data)

prediction = classifier.predict(std_data)

print(prediction)

if(prediction[0]==0):
    print('pasien resiko rendah')
elif(prediction[0]==1):
    print('pasien resiko menengah')
else : 
    print('pasien resiko tinggi')

[[-1.10425321  0.36976548  0.25502279 -0.52127416 -0.4852155  -0.53208757]]
[0]
pasien resiko rendah


c:\Users\62831\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


SIMPAN MODEL 

In [26]:
import pickle

In [27]:
filename = 'Maternal_model.sav'
pickle.dump(classifier, open(filename,'wb'))